title: Salami Neck
description:
tagline:
permalink: /:title/
markdown: kramdown
defaults:
# You can use the following to enable comments on all posts.
  - scope:
      type: posts
    values:
      # https://applause-button.com/
      applause_button: true
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
