title: Adam Walser
tagline: 'Eats cereal with his BMX gloves on'
description: Adam Walser's blog
author:
  name: Adam Walser
permalink: /:title/
paginate: 2
paginate_path: /page:num/
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
