title: Adam Walser
description: Adam Walser's blog
author:
  name: Adam Walser
permalink: /:title/
paginate: 4
paginate_path: /page:num/
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
